### ISSUE TITLE
Cloudflare Workers 缓存！

### ISSUE THREAD

**Issue by ocoke** [yfun-lab/gh-worker-kv#2]
![image](https://user-images.githubusercontent.com/71591824/149659731-8368d728-ca21-4fd0-a5c9-5db7232c9f3c.png)
![image](https://user-images.githubusercontent.com/71591824/149659779-48cd1c4a-f907-4326-b2ef-c2fc56af059b.png)

**Comment by ocoke** [comment]
问题出在获取的时候。
发送的 Get 请求被 Cloudflare Workers 缓存下来。

**Comment by ocoke** [comment]
设置的时候会先获取数据库一遍，所以现在还容易造成数据的丢失。

**Comment by oCoke** [comment]
要么就是:
```
Users <=> Cloudflare Workers <=> Backend <=> GitHub
```

**Comment by ocoke** [comment]
这东西多刷新几次还会反复横跳？？

**Comment by ocoke** [comment]
要我记得好像这样获取的没用
![image](https://user-images.githubusercontent.com/71591824/149659946-a6af3af7-af44-4d03-ac84-beec7d048ada.png)

**Comment by ocoke** [comment]
![image](https://user-images.githubusercontent.com/71591824/149660230-0ea1b6dd-2ee4-48c6-9835-c11ad6597e01.png)
行，也没用。

**Comment by ocoke** [comment]
也有可能是 GitHub 方面的问题

**Comment by ocoke** [comment]
确实：https://stackoverflow.com/questions/62785962/get-raw-file-from-github-without-waiting-for-5-minute-cache-update

或许先拿到版本号先
